### ISSUE TITLE
Disable automatic Closed surface creation

### ISSUE THREAD

**Issue by dfajtai** [SlicerRt/SlicerRT#258] opened 2024-11-12 14:49 UTC
Is it possible to disable/prevent the automatic calculation of the closed surface representation at the loading phase? In some cases, this feature could save time for the user.

**Comment by cpinter** [comment] 2024-11-12 15:58
In general it is desired to do the conversion because if the user does not see the data they will suppose that loading has failed.

But it could be possible to add this in the application settings, but thus far there are no settings specific to SlicerRT so we'd need to add a new settings panel with this option.

Another solution could be to tweak the representation converters so that the conversion goes though ribbons, it is much faster. The default is the second path in this screenshot, and by changing some weights in `.slicerrc.py` you could divert the converter to use the first one.
![image](https://github.com/user-attachments/assets/1dfb179d-8cb3-4bea-9233-15edcd6f2805)

**Comment by cpinter** [comment] 2024-12-16 15:43
Since there is no answer for more then a month, I suppose the issue is resolved. Closing it but feel free to reopen if there is more to discuss. Thanks!

**Closed as completed by cpinter** 2024-12-16 15:43 UTC
